name: CD
on:
  push:
    branches: ["main"]
jobs:
  deploying:
    needs: [publishing]
    runs-on: ubuntu-latest
    steps:
      - name: Pulling and rebuilding images on the host machine
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop practice-3
            docker rm practice-3
            docker pull ghcr.io/ukoricpaw/devops-practice-3:main
            docker run -d --name practice-3 -p 8080:8080 ghcr.io/ukoricpaw/devops-practice-3:main
            docker image prune
